version: '3.8'

services:
  scrumix-postgres:
    image: postgres:16
    container_name: scrumix-postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - scrumix_postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d/
    networks:
      - scrumix-local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  scrumix-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: scrumix-keycloak-local
    restart: unless-stopped
    environment:
      # Keycloak Admin
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      
      # Database Configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://scrumix-postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      
      # Development Settings
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      
      # Development Mode
      KC_DEV: true
    ports:
      - "8080:8080"
    volumes:
      - scrumix_keycloak_data:/opt/keycloak/data
    depends_on:
      scrumix-postgres:
        condition: service_healthy
    networks:
      - scrumix-local
    command: start-dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  scrumix-local:
    driver: bridge

volumes:
  scrumix_postgres_data:
  scrumix_keycloak_data:
