"""add_first_last_name_and_date_format_to_users

Revision ID: 1964dcb11413
Revises: 95434eca23bd
Create Date: 2025-08-22 22:14:10.819167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1964dcb11413'
down_revision: Union[str, Sequence[str], None] = '95434eca23bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('date_format', sa.String(length=20), nullable=True, server_default='YYYY-MM-DD'))
    
    # Populate existing users' name fields from full_name
    op.execute("""
        UPDATE users 
        SET first_name = CASE 
            WHEN full_name IS NOT NULL AND TRIM(full_name) != '' THEN 
                CASE 
                    WHEN INSTR(full_name, ' ') > 0 THEN SUBSTR(full_name, 1, INSTR(full_name, ' ') - 1)
                    ELSE full_name 
                END
            ELSE NULL
        END,
        last_name = CASE 
            WHEN full_name IS NOT NULL AND TRIM(full_name) != '' AND INSTR(full_name, ' ') > 0 THEN 
                SUBSTR(full_name, INSTR(full_name, ' ') + 1)
            ELSE NULL
        END,
        date_format = 'YYYY-MM-DD'
        WHERE full_name IS NOT NULL OR date_format IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_format')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
